version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672 # RabbitMQ server
      - 15672:15672 # RabbitMQ management plugin
