// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package rabbitmqutils

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// MockSpecificMessageHandler is an autogenerated mock type for the SpecificMessageHandler type
type MockSpecificMessageHandler struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: message
func (_m *MockSpecificMessageHandler) HandleMessage(message interface{}) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageType provides a mock function with given fields:
func (_m *MockSpecificMessageHandler) MessageType() reflect.Type {
	ret := _m.Called()

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}
