// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package rabbitmqutils

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageConsumerClient is an autogenerated mock type for the MessageConsumerClient type
type MockMessageConsumerClient struct {
	mock.Mock
}

// CancelConsuming provides a mock function with given fields: queue
func (_m *MockMessageConsumerClient) CancelConsuming(queue string) error {
	ret := _m.Called(queue)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(queue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConsumeMessages provides a mock function with given fields: queue
func (_m *MockMessageConsumerClient) ConsumeMessages(queue string) (<-chan amqp.Delivery, error) {
	ret := _m.Called(queue)

	var r0 <-chan amqp.Delivery
	if rf, ok := ret.Get(0).(func(string) <-chan amqp.Delivery); ok {
		r0 = rf(queue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(queue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
