// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package rabbitmqutils

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// MockClockInterface is an autogenerated mock type for the DialerInterface type
type MockClockInterface struct {
	mock.Mock
}

// Dial provides a mock function with given fields:
func (_m *MockClockInterface) Time() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(time.Time)
		}
	}

	return r0
}
