// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package rabbitmqutils

import (
	amqp "github.com/streadway/amqp"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageHandler is an autogenerated mock type for the MessageHandler type
type MockMessageHandler struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: message
func (_m *MockMessageHandler) HandleMessage(message amqp.Delivery) {
	_m.Called(message)
}
